name: loginpage
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.7
  google_fonts: ^6.1.0
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo1.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
